// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Xl22Ln48nLATsQ3zCkLj_j_M0kobCyU',
    appId: '1:748152159880:web:94c54c63a838fb9cd5e93d',
    messagingSenderId: '748152159880',
    projectId: 'qrexample-3cd3b',
    authDomain: 'qrexample-3cd3b.firebaseapp.com',
    storageBucket: 'qrexample-3cd3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zAZwe8xLJVOnN-9RneBjRe4Q0ARHMrA',
    appId: '1:748152159880:android:aa8bf64eab20d5f7d5e93d',
    messagingSenderId: '748152159880',
    projectId: 'qrexample-3cd3b',
    storageBucket: 'qrexample-3cd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHosVxyNyYHiCZjNkXEgjPNtKaTGpz_Cg',
    appId: '1:748152159880:ios:919ad11938a40c7cd5e93d',
    messagingSenderId: '748152159880',
    projectId: 'qrexample-3cd3b',
    storageBucket: 'qrexample-3cd3b.firebasestorage.app',
    iosBundleId: 'com.qrexample.qrexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHosVxyNyYHiCZjNkXEgjPNtKaTGpz_Cg',
    appId: '1:748152159880:ios:919ad11938a40c7cd5e93d',
    messagingSenderId: '748152159880',
    projectId: 'qrexample-3cd3b',
    storageBucket: 'qrexample-3cd3b.firebasestorage.app',
    iosBundleId: 'com.qrexample.qrexample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Xl22Ln48nLATsQ3zCkLj_j_M0kobCyU',
    appId: '1:748152159880:web:b296f4539773059bd5e93d',
    messagingSenderId: '748152159880',
    projectId: 'qrexample-3cd3b',
    authDomain: 'qrexample-3cd3b.firebaseapp.com',
    storageBucket: 'qrexample-3cd3b.firebasestorage.app',
  );
}
